#include <defs.hxx>
#include <loop_device.hxx>
#include <sum.hxx>
#include <vect.hxx>

#include <cctk.h>
#include <cctk_Arguments.h>
#include <cctk_Parameters.h>

#include <cassert>
#include <cmath>

namespace BoxInBox {
using namespace Loop;

constexpr int max_num_regions = 100;
constexpr int max_num_levels = 30;

enum class shape_t { sphere, cube };

template <typename T>
constexpr bool should_refine_sphere(const vect<T, dim> &X,
                                    const vect<T, dim> &Rmax) {
  return sum(pow2(X / Rmax)) <= 1;
}

template <typename T>
constexpr bool should_refine_cube(const vect<T, dim> &X,
                                  const vect<T, dim> &Rmax) {
  using std::abs;
  return maximum(abs(X / Rmax)) <= 1;
}

template <typename T>
constexpr bool should_refine(const shape_t shape, const vect<T, dim> &X,
                             const vect<T, dim> &Rmax) {
  switch (shape) {
  case shape_t::sphere:
    return should_refine_sphere(X, Rmax);
  case shape_t::cube:
    return should_refine_cube(X, Rmax);
  default:
    assert(0);
    return false;
  };
}

extern "C" void BoxInBox_Init(CCTK_ARGUMENTS) {
  DECLARE_CCTK_ARGUMENTSX_BoxInBox_Init;
  DECLARE_CCTK_PARAMETERS;

  // Copy parameters into grid scalars. Only regions below num_regions are active;
  // this keeps default parameter values from accidentally creating boxes.
  const bool active_params[max_num_regions] = {
      bool(active_1),
      bool(active_2),
      bool(active_3),
      bool(active_4),
      bool(active_5),
      bool(active_6),
      bool(active_7),
      bool(active_8),
      bool(active_9),
      bool(active_10),
      bool(active_11),
      bool(active_12),
      bool(active_13),
      bool(active_14),
      bool(active_15),
      bool(active_16),
      bool(active_17),
      bool(active_18),
      bool(active_19),
      bool(active_20),
      bool(active_21),
      bool(active_22),
      bool(active_23),
      bool(active_24),
      bool(active_25),
      bool(active_26),
      bool(active_27),
      bool(active_28),
      bool(active_29),
      bool(active_30),
      bool(active_31),
      bool(active_32),
      bool(active_33),
      bool(active_34),
      bool(active_35),
      bool(active_36),
      bool(active_37),
      bool(active_38),
      bool(active_39),
      bool(active_40),
      bool(active_41),
      bool(active_42),
      bool(active_43),
      bool(active_44),
      bool(active_45),
      bool(active_46),
      bool(active_47),
      bool(active_48),
      bool(active_49),
      bool(active_50),
      bool(active_51),
      bool(active_52),
      bool(active_53),
      bool(active_54),
      bool(active_55),
      bool(active_56),
      bool(active_57),
      bool(active_58),
      bool(active_59),
      bool(active_60),
      bool(active_61),
      bool(active_62),
      bool(active_63),
      bool(active_64),
      bool(active_65),
      bool(active_66),
      bool(active_67),
      bool(active_68),
      bool(active_69),
      bool(active_70),
      bool(active_71),
      bool(active_72),
      bool(active_73),
      bool(active_74),
      bool(active_75),
      bool(active_76),
      bool(active_77),
      bool(active_78),
      bool(active_79),
      bool(active_80),
      bool(active_81),
      bool(active_82),
      bool(active_83),
      bool(active_84),
      bool(active_85),
      bool(active_86),
      bool(active_87),
      bool(active_88),
      bool(active_89),
      bool(active_90),
      bool(active_91),
      bool(active_92),
      bool(active_93),
      bool(active_94),
      bool(active_95),
      bool(active_96),
      bool(active_97),
      bool(active_98),
      bool(active_99),
      bool(active_100)};
  const int num_levels_params[max_num_regions] = {
      int(num_levels_1),
      int(num_levels_2),
      int(num_levels_3),
      int(num_levels_4),
      int(num_levels_5),
      int(num_levels_6),
      int(num_levels_7),
      int(num_levels_8),
      int(num_levels_9),
      int(num_levels_10),
      int(num_levels_11),
      int(num_levels_12),
      int(num_levels_13),
      int(num_levels_14),
      int(num_levels_15),
      int(num_levels_16),
      int(num_levels_17),
      int(num_levels_18),
      int(num_levels_19),
      int(num_levels_20),
      int(num_levels_21),
      int(num_levels_22),
      int(num_levels_23),
      int(num_levels_24),
      int(num_levels_25),
      int(num_levels_26),
      int(num_levels_27),
      int(num_levels_28),
      int(num_levels_29),
      int(num_levels_30),
      int(num_levels_31),
      int(num_levels_32),
      int(num_levels_33),
      int(num_levels_34),
      int(num_levels_35),
      int(num_levels_36),
      int(num_levels_37),
      int(num_levels_38),
      int(num_levels_39),
      int(num_levels_40),
      int(num_levels_41),
      int(num_levels_42),
      int(num_levels_43),
      int(num_levels_44),
      int(num_levels_45),
      int(num_levels_46),
      int(num_levels_47),
      int(num_levels_48),
      int(num_levels_49),
      int(num_levels_50),
      int(num_levels_51),
      int(num_levels_52),
      int(num_levels_53),
      int(num_levels_54),
      int(num_levels_55),
      int(num_levels_56),
      int(num_levels_57),
      int(num_levels_58),
      int(num_levels_59),
      int(num_levels_60),
      int(num_levels_61),
      int(num_levels_62),
      int(num_levels_63),
      int(num_levels_64),
      int(num_levels_65),
      int(num_levels_66),
      int(num_levels_67),
      int(num_levels_68),
      int(num_levels_69),
      int(num_levels_70),
      int(num_levels_71),
      int(num_levels_72),
      int(num_levels_73),
      int(num_levels_74),
      int(num_levels_75),
      int(num_levels_76),
      int(num_levels_77),
      int(num_levels_78),
      int(num_levels_79),
      int(num_levels_80),
      int(num_levels_81),
      int(num_levels_82),
      int(num_levels_83),
      int(num_levels_84),
      int(num_levels_85),
      int(num_levels_86),
      int(num_levels_87),
      int(num_levels_88),
      int(num_levels_89),
      int(num_levels_90),
      int(num_levels_91),
      int(num_levels_92),
      int(num_levels_93),
      int(num_levels_94),
      int(num_levels_95),
      int(num_levels_96),
      int(num_levels_97),
      int(num_levels_98),
      int(num_levels_99),
      int(num_levels_100)};
  const CCTK_REAL position_x_params[max_num_regions] = {
      position_x_1,
      position_x_2,
      position_x_3,
      position_x_4,
      position_x_5,
      position_x_6,
      position_x_7,
      position_x_8,
      position_x_9,
      position_x_10,
      position_x_11,
      position_x_12,
      position_x_13,
      position_x_14,
      position_x_15,
      position_x_16,
      position_x_17,
      position_x_18,
      position_x_19,
      position_x_20,
      position_x_21,
      position_x_22,
      position_x_23,
      position_x_24,
      position_x_25,
      position_x_26,
      position_x_27,
      position_x_28,
      position_x_29,
      position_x_30,
      position_x_31,
      position_x_32,
      position_x_33,
      position_x_34,
      position_x_35,
      position_x_36,
      position_x_37,
      position_x_38,
      position_x_39,
      position_x_40,
      position_x_41,
      position_x_42,
      position_x_43,
      position_x_44,
      position_x_45,
      position_x_46,
      position_x_47,
      position_x_48,
      position_x_49,
      position_x_50,
      position_x_51,
      position_x_52,
      position_x_53,
      position_x_54,
      position_x_55,
      position_x_56,
      position_x_57,
      position_x_58,
      position_x_59,
      position_x_60,
      position_x_61,
      position_x_62,
      position_x_63,
      position_x_64,
      position_x_65,
      position_x_66,
      position_x_67,
      position_x_68,
      position_x_69,
      position_x_70,
      position_x_71,
      position_x_72,
      position_x_73,
      position_x_74,
      position_x_75,
      position_x_76,
      position_x_77,
      position_x_78,
      position_x_79,
      position_x_80,
      position_x_81,
      position_x_82,
      position_x_83,
      position_x_84,
      position_x_85,
      position_x_86,
      position_x_87,
      position_x_88,
      position_x_89,
      position_x_90,
      position_x_91,
      position_x_92,
      position_x_93,
      position_x_94,
      position_x_95,
      position_x_96,
      position_x_97,
      position_x_98,
      position_x_99,
      position_x_100};
  const CCTK_REAL position_y_params[max_num_regions] = {
      position_y_1,
      position_y_2,
      position_y_3,
      position_y_4,
      position_y_5,
      position_y_6,
      position_y_7,
      position_y_8,
      position_y_9,
      position_y_10,
      position_y_11,
      position_y_12,
      position_y_13,
      position_y_14,
      position_y_15,
      position_y_16,
      position_y_17,
      position_y_18,
      position_y_19,
      position_y_20,
      position_y_21,
      position_y_22,
      position_y_23,
      position_y_24,
      position_y_25,
      position_y_26,
      position_y_27,
      position_y_28,
      position_y_29,
      position_y_30,
      position_y_31,
      position_y_32,
      position_y_33,
      position_y_34,
      position_y_35,
      position_y_36,
      position_y_37,
      position_y_38,
      position_y_39,
      position_y_40,
      position_y_41,
      position_y_42,
      position_y_43,
      position_y_44,
      position_y_45,
      position_y_46,
      position_y_47,
      position_y_48,
      position_y_49,
      position_y_50,
      position_y_51,
      position_y_52,
      position_y_53,
      position_y_54,
      position_y_55,
      position_y_56,
      position_y_57,
      position_y_58,
      position_y_59,
      position_y_60,
      position_y_61,
      position_y_62,
      position_y_63,
      position_y_64,
      position_y_65,
      position_y_66,
      position_y_67,
      position_y_68,
      position_y_69,
      position_y_70,
      position_y_71,
      position_y_72,
      position_y_73,
      position_y_74,
      position_y_75,
      position_y_76,
      position_y_77,
      position_y_78,
      position_y_79,
      position_y_80,
      position_y_81,
      position_y_82,
      position_y_83,
      position_y_84,
      position_y_85,
      position_y_86,
      position_y_87,
      position_y_88,
      position_y_89,
      position_y_90,
      position_y_91,
      position_y_92,
      position_y_93,
      position_y_94,
      position_y_95,
      position_y_96,
      position_y_97,
      position_y_98,
      position_y_99,
      position_y_100};
  const CCTK_REAL position_z_params[max_num_regions] = {
      position_z_1,
      position_z_2,
      position_z_3,
      position_z_4,
      position_z_5,
      position_z_6,
      position_z_7,
      position_z_8,
      position_z_9,
      position_z_10,
      position_z_11,
      position_z_12,
      position_z_13,
      position_z_14,
      position_z_15,
      position_z_16,
      position_z_17,
      position_z_18,
      position_z_19,
      position_z_20,
      position_z_21,
      position_z_22,
      position_z_23,
      position_z_24,
      position_z_25,
      position_z_26,
      position_z_27,
      position_z_28,
      position_z_29,
      position_z_30,
      position_z_31,
      position_z_32,
      position_z_33,
      position_z_34,
      position_z_35,
      position_z_36,
      position_z_37,
      position_z_38,
      position_z_39,
      position_z_40,
      position_z_41,
      position_z_42,
      position_z_43,
      position_z_44,
      position_z_45,
      position_z_46,
      position_z_47,
      position_z_48,
      position_z_49,
      position_z_50,
      position_z_51,
      position_z_52,
      position_z_53,
      position_z_54,
      position_z_55,
      position_z_56,
      position_z_57,
      position_z_58,
      position_z_59,
      position_z_60,
      position_z_61,
      position_z_62,
      position_z_63,
      position_z_64,
      position_z_65,
      position_z_66,
      position_z_67,
      position_z_68,
      position_z_69,
      position_z_70,
      position_z_71,
      position_z_72,
      position_z_73,
      position_z_74,
      position_z_75,
      position_z_76,
      position_z_77,
      position_z_78,
      position_z_79,
      position_z_80,
      position_z_81,
      position_z_82,
      position_z_83,
      position_z_84,
      position_z_85,
      position_z_86,
      position_z_87,
      position_z_88,
      position_z_89,
      position_z_90,
      position_z_91,
      position_z_92,
      position_z_93,
      position_z_94,
      position_z_95,
      position_z_96,
      position_z_97,
      position_z_98,
      position_z_99,
      position_z_100};
  const CCTK_REAL *const radius_params[max_num_regions] = {
      radius_1,
      radius_2,
      radius_3,
      radius_4,
      radius_5,
      radius_6,
      radius_7,
      radius_8,
      radius_9,
      radius_10,
      radius_11,
      radius_12,
      radius_13,
      radius_14,
      radius_15,
      radius_16,
      radius_17,
      radius_18,
      radius_19,
      radius_20,
      radius_21,
      radius_22,
      radius_23,
      radius_24,
      radius_25,
      radius_26,
      radius_27,
      radius_28,
      radius_29,
      radius_30,
      radius_31,
      radius_32,
      radius_33,
      radius_34,
      radius_35,
      radius_36,
      radius_37,
      radius_38,
      radius_39,
      radius_40,
      radius_41,
      radius_42,
      radius_43,
      radius_44,
      radius_45,
      radius_46,
      radius_47,
      radius_48,
      radius_49,
      radius_50,
      radius_51,
      radius_52,
      radius_53,
      radius_54,
      radius_55,
      radius_56,
      radius_57,
      radius_58,
      radius_59,
      radius_60,
      radius_61,
      radius_62,
      radius_63,
      radius_64,
      radius_65,
      radius_66,
      radius_67,
      radius_68,
      radius_69,
      radius_70,
      radius_71,
      radius_72,
      radius_73,
      radius_74,
      radius_75,
      radius_76,
      radius_77,
      radius_78,
      radius_79,
      radius_80,
      radius_81,
      radius_82,
      radius_83,
      radius_84,
      radius_85,
      radius_86,
      radius_87,
      radius_88,
      radius_89,
      radius_90,
      radius_91,
      radius_92,
      radius_93,
      radius_94,
      radius_95,
      radius_96,
      radius_97,
      radius_98,
      radius_99,
      radius_100};
  const CCTK_REAL *const radius_x_params[max_num_regions] = {
      radius_x_1,
      radius_x_2,
      radius_x_3,
      radius_x_4,
      radius_x_5,
      radius_x_6,
      radius_x_7,
      radius_x_8,
      radius_x_9,
      radius_x_10,
      radius_x_11,
      radius_x_12,
      radius_x_13,
      radius_x_14,
      radius_x_15,
      radius_x_16,
      radius_x_17,
      radius_x_18,
      radius_x_19,
      radius_x_20,
      radius_x_21,
      radius_x_22,
      radius_x_23,
      radius_x_24,
      radius_x_25,
      radius_x_26,
      radius_x_27,
      radius_x_28,
      radius_x_29,
      radius_x_30,
      radius_x_31,
      radius_x_32,
      radius_x_33,
      radius_x_34,
      radius_x_35,
      radius_x_36,
      radius_x_37,
      radius_x_38,
      radius_x_39,
      radius_x_40,
      radius_x_41,
      radius_x_42,
      radius_x_43,
      radius_x_44,
      radius_x_45,
      radius_x_46,
      radius_x_47,
      radius_x_48,
      radius_x_49,
      radius_x_50,
      radius_x_51,
      radius_x_52,
      radius_x_53,
      radius_x_54,
      radius_x_55,
      radius_x_56,
      radius_x_57,
      radius_x_58,
      radius_x_59,
      radius_x_60,
      radius_x_61,
      radius_x_62,
      radius_x_63,
      radius_x_64,
      radius_x_65,
      radius_x_66,
      radius_x_67,
      radius_x_68,
      radius_x_69,
      radius_x_70,
      radius_x_71,
      radius_x_72,
      radius_x_73,
      radius_x_74,
      radius_x_75,
      radius_x_76,
      radius_x_77,
      radius_x_78,
      radius_x_79,
      radius_x_80,
      radius_x_81,
      radius_x_82,
      radius_x_83,
      radius_x_84,
      radius_x_85,
      radius_x_86,
      radius_x_87,
      radius_x_88,
      radius_x_89,
      radius_x_90,
      radius_x_91,
      radius_x_92,
      radius_x_93,
      radius_x_94,
      radius_x_95,
      radius_x_96,
      radius_x_97,
      radius_x_98,
      radius_x_99,
      radius_x_100};
  const CCTK_REAL *const radius_y_params[max_num_regions] = {
      radius_y_1,
      radius_y_2,
      radius_y_3,
      radius_y_4,
      radius_y_5,
      radius_y_6,
      radius_y_7,
      radius_y_8,
      radius_y_9,
      radius_y_10,
      radius_y_11,
      radius_y_12,
      radius_y_13,
      radius_y_14,
      radius_y_15,
      radius_y_16,
      radius_y_17,
      radius_y_18,
      radius_y_19,
      radius_y_20,
      radius_y_21,
      radius_y_22,
      radius_y_23,
      radius_y_24,
      radius_y_25,
      radius_y_26,
      radius_y_27,
      radius_y_28,
      radius_y_29,
      radius_y_30,
      radius_y_31,
      radius_y_32,
      radius_y_33,
      radius_y_34,
      radius_y_35,
      radius_y_36,
      radius_y_37,
      radius_y_38,
      radius_y_39,
      radius_y_40,
      radius_y_41,
      radius_y_42,
      radius_y_43,
      radius_y_44,
      radius_y_45,
      radius_y_46,
      radius_y_47,
      radius_y_48,
      radius_y_49,
      radius_y_50,
      radius_y_51,
      radius_y_52,
      radius_y_53,
      radius_y_54,
      radius_y_55,
      radius_y_56,
      radius_y_57,
      radius_y_58,
      radius_y_59,
      radius_y_60,
      radius_y_61,
      radius_y_62,
      radius_y_63,
      radius_y_64,
      radius_y_65,
      radius_y_66,
      radius_y_67,
      radius_y_68,
      radius_y_69,
      radius_y_70,
      radius_y_71,
      radius_y_72,
      radius_y_73,
      radius_y_74,
      radius_y_75,
      radius_y_76,
      radius_y_77,
      radius_y_78,
      radius_y_79,
      radius_y_80,
      radius_y_81,
      radius_y_82,
      radius_y_83,
      radius_y_84,
      radius_y_85,
      radius_y_86,
      radius_y_87,
      radius_y_88,
      radius_y_89,
      radius_y_90,
      radius_y_91,
      radius_y_92,
      radius_y_93,
      radius_y_94,
      radius_y_95,
      radius_y_96,
      radius_y_97,
      radius_y_98,
      radius_y_99,
      radius_y_100};
  const CCTK_REAL *const radius_z_params[max_num_regions] = {
      radius_z_1,
      radius_z_2,
      radius_z_3,
      radius_z_4,
      radius_z_5,
      radius_z_6,
      radius_z_7,
      radius_z_8,
      radius_z_9,
      radius_z_10,
      radius_z_11,
      radius_z_12,
      radius_z_13,
      radius_z_14,
      radius_z_15,
      radius_z_16,
      radius_z_17,
      radius_z_18,
      radius_z_19,
      radius_z_20,
      radius_z_21,
      radius_z_22,
      radius_z_23,
      radius_z_24,
      radius_z_25,
      radius_z_26,
      radius_z_27,
      radius_z_28,
      radius_z_29,
      radius_z_30,
      radius_z_31,
      radius_z_32,
      radius_z_33,
      radius_z_34,
      radius_z_35,
      radius_z_36,
      radius_z_37,
      radius_z_38,
      radius_z_39,
      radius_z_40,
      radius_z_41,
      radius_z_42,
      radius_z_43,
      radius_z_44,
      radius_z_45,
      radius_z_46,
      radius_z_47,
      radius_z_48,
      radius_z_49,
      radius_z_50,
      radius_z_51,
      radius_z_52,
      radius_z_53,
      radius_z_54,
      radius_z_55,
      radius_z_56,
      radius_z_57,
      radius_z_58,
      radius_z_59,
      radius_z_60,
      radius_z_61,
      radius_z_62,
      radius_z_63,
      radius_z_64,
      radius_z_65,
      radius_z_66,
      radius_z_67,
      radius_z_68,
      radius_z_69,
      radius_z_70,
      radius_z_71,
      radius_z_72,
      radius_z_73,
      radius_z_74,
      radius_z_75,
      radius_z_76,
      radius_z_77,
      radius_z_78,
      radius_z_79,
      radius_z_80,
      radius_z_81,
      radius_z_82,
      radius_z_83,
      radius_z_84,
      radius_z_85,
      radius_z_86,
      radius_z_87,
      radius_z_88,
      radius_z_89,
      radius_z_90,
      radius_z_91,
      radius_z_92,
      radius_z_93,
      radius_z_94,
      radius_z_95,
      radius_z_96,
      radius_z_97,
      radius_z_98,
      radius_z_99,
      radius_z_100};

  for (int region = 0; region < max_num_regions; ++region) {
    active[region] = region < num_regions && active_params[region];
    num_levels[region] = num_levels_params[region];
    position_x[region] = position_x_params[region];
    position_y[region] = position_y_params[region];
    position_z[region] = position_z_params[region];
    for (int level = 0; level < max_num_levels; ++level) {
      radius[level + max_num_levels * region] = radius_params[region][level];
      radius_x[level + max_num_levels * region] =
          radius_x_params[region][level];
      radius_y[level + max_num_levels * region] =
          radius_y_params[region][level];
      radius_z[level + max_num_levels * region] =
          radius_z_params[region][level];
    }
  }
}

extern "C" void BoxInBox_Setup(CCTK_ARGUMENTS) {
  DECLARE_CCTK_ARGUMENTSX_BoxInBox_Setup;
  DECLARE_CCTK_PARAMETERS;

  // Refine only patch 0
  if (cctk_patch != 0)
    return;

  const auto get_shape = [](const auto &shape) {
    if (CCTK_EQUALS(shape, "sphere"))
      return shape_t::sphere;
    if (CCTK_EQUALS(shape, "cube"))
      return shape_t::cube;
    CCTK_ERROR("internal error");
  };
  const char *const shape_params[max_num_regions] = {
      shape_1,
      shape_2,
      shape_3,
      shape_4,
      shape_5,
      shape_6,
      shape_7,
      shape_8,
      shape_9,
      shape_10,
      shape_11,
      shape_12,
      shape_13,
      shape_14,
      shape_15,
      shape_16,
      shape_17,
      shape_18,
      shape_19,
      shape_20,
      shape_21,
      shape_22,
      shape_23,
      shape_24,
      shape_25,
      shape_26,
      shape_27,
      shape_28,
      shape_29,
      shape_30,
      shape_31,
      shape_32,
      shape_33,
      shape_34,
      shape_35,
      shape_36,
      shape_37,
      shape_38,
      shape_39,
      shape_40,
      shape_41,
      shape_42,
      shape_43,
      shape_44,
      shape_45,
      shape_46,
      shape_47,
      shape_48,
      shape_49,
      shape_50,
      shape_51,
      shape_52,
      shape_53,
      shape_54,
      shape_55,
      shape_56,
      shape_57,
      shape_58,
      shape_59,
      shape_60,
      shape_61,
      shape_62,
      shape_63,
      shape_64,
      shape_65,
      shape_66,
      shape_67,
      shape_68,
      shape_69,
      shape_70,
      shape_71,
      shape_72,
      shape_73,
      shape_74,
      shape_75,
      shape_76,
      shape_77,
      shape_78,
      shape_79,
      shape_80,
      shape_81,
      shape_82,
      shape_83,
      shape_84,
      shape_85,
      shape_86,
      shape_87,
      shape_88,
      shape_89,
      shape_90,
      shape_91,
      shape_92,
      shape_93,
      shape_94,
      shape_95,
      shape_96,
      shape_97,
      shape_98,
      shape_99,
      shape_100};
  const auto shapes = vect<shape_t, max_num_regions>::make(
      [&](int region) { return get_shape(shape_params[region]); });

  // The level about which we're deciding on, i.e. the current level + 1
  using std::ilogb;
  const int level = ilogb(CCTK_REAL(cctk_levfac[0])) + 1;

  const auto active1 = vect<bool, max_num_regions>::make(
      [&](int region) { return bool(active[region]); });
  const auto num_levels1 = vect<int, max_num_regions>::make(
      [&](int region) { return int(num_levels[region]); });
  const auto positions1 =
      vect<vect<CCTK_REAL, dim>, max_num_regions>::make([&](int region) {
        return vect<CCTK_REAL, dim>{position_x[region], position_y[region],
                                    position_z[region]};
      });
  const auto radii1 =
      vect<vect<CCTK_REAL, dim>, max_num_regions>::make([&](int region) {
        const int level_region = level + max_num_levels * region;
        return vect<CCTK_REAL, dim>{
            radius_x[level_region] < 0 ? radius[level_region]
                                       : radius_x[level_region],
            radius_y[level_region] < 0 ? radius[level_region]
                                       : radius_y[level_region],
            radius_z[level_region] < 0 ? radius[level_region]
                                       : radius_z[level_region]};
      });

  for (int region = 0; region < max_num_regions; ++region)
    if (active1[region])
      if (level < num_levels1[region])
        if (any(radii1[region] <= 0))
          CCTK_VERROR("Non-positive radius found: Refined region %d, "
                      "refinement level %d, radii are [%.17g,%.17g,%.17g]",
                      region, level, double(radii1[region][0]),
                      double(radii1[region][1]), double(radii1[region][2]));

  const auto positions2 = positions1;

  grid.loop_int_device<1, 1, 1>(
      grid.nghostzones,
      [=] CCTK_DEVICE(const PointDesc &p) CCTK_ATTRIBUTE_ALWAYS_INLINE {
        bool do_refine = false;

        for (int region = 0; region < max_num_regions; ++region) {
          if (active1[region]) {
            if (level < num_levels1[region]) {
              const auto position = positions2[region];
              const auto radii = radii1[region];
              // Decrease the box radius by one grid spacing since AMReX seems
              // to expand the refined region by one cell
              const auto Rmax = radii - p.DX;
              const bool sr =
                  should_refine(shapes[region], p.X - position, Rmax);
              do_refine |= sr;
            }
          }
        }

        regrid_error(p.I) = do_refine ? 1 : 0;
      });
}

} // namespace BoxInBox
